
trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'
  dockerImageLabel: '$(Build.BuildId)'
  tag: '$(dockerId)/$(dockerImageName):$(dockerImageLabel)'
  dockerRegistryServiceConnectionId: '{{ dockerRegistryServiceConnection }}'

stages:
- stage: CI
  displayName: Build and push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo dockerId: $(dockerId)
        echo tag: $(tag)
      displayName: Show variables
    #- task: Docker@2
    #  displayName: Docker - Build
    #  inputs:
    #    command: build
    #    repository: '$(dockerImageName)'
    #    tags: |
    #      latest
    #      $(dockerImageLabel)
    - script: |
        docker build -t 'avalier.azurecr.io/$(dockerImageName)' ./src
      displayName: Docker - Build
    - script: |
        docker image list | grep avalier
      displayName: Docker - List
    - task: Docker@2
      displayName: Docker - Login
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection
    - task: Docker@2
      displayName: Docker - Push
      inputs:
        command: push
        containerRegistry: dockerRegistryServiceConnection
        repository: '$(dockerImageName)'
        tags: |
          latest
          $(dockerImageLabel)

    #steps:
    #- task: Docker@2
    #  displayName: Build and push an image to container registry
    #  inputs:
    #    command: buildAndPush
    #    repository: $(imageRepository)
    #    dockerfile: $(dockerfilePath)
    #    containerRegistry: $(dockerRegistryServiceConnection)
    #    tags: |
    #      $(tag)