
trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'
  dockerImageLabel: '$(Build.BuildId)'
  dockerRegistryServiceConnectionId: '{{ dockerRegistryServiceConnection }}'

stages:
- stage: CI
  displayName: Build and push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo dockerId: $(dockerId)
        echo tag: $(tag)
      displayName: Show variables
    - task: Docker@2
      displayName: Docker - Login
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection
    - script: |
        docker build -t '$(dockerId)/$(dockerImageName):latest' ./src
      displayName: Docker - Build
    - script: |
        docker tag '$(dockerId)/$(dockerImageName):latest' '$(dockerId)/$(dockerImageName):$(dockerImageLabel)'
        docker tag '$(dockerId)/$(dockerImageName):latest' '$(dockerId)/$(dockerImageName):$(Build.SourceVersion)'
      displayName: Docker - Tag
    - script: |
        docker image list | grep avalier
      displayName: Docker - List
    - task: Docker@2
      displayName: Docker - Push
      inputs:
        command: push
        containerRegistry: dockerRegistryServiceConnection
        repository: '$(dockerImageName)'
        tags: |
          latest
          $(dockerImageLabel)
          $(Build.SourceVersion)
