#https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops
#condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: $(vmImageName)

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'

jobs:  
- job: BuildAndTest
  displayName: Build & Test
  steps:
  - template: templates/dotnet-build-and-test.yml
- job: Create Docker Image
  dependsOn: BuildAndTest
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  steps:
  -script: echo Create Docker Image
