
trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'
  trivyCachePath: '$(Pipeline.Workspace)/.cache/trivy'

stages:
- stage: CI
  displayName: Build and push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - script: |
        echo dockerId: $(dockerId)
        echo tag: $(tag)
        echo connection: dockerRegistryServiceConnection
      displayName: Show variables

    - task: Docker@2
      displayName: Docker - Login
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection

    #- task: CacheBeta@0
    #  inputs:
    #    key: trivy | $(Agent.OS)
    #    path: $(trivyCachePath)
    #  displayName: Docker - Trivy Caching (Container Security Analysis by Aquasec)
    #--cache-dir '$(trivyCachePath)'

    - script: |
        sudo apt-get -y install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v0.0.15/trivy_0.0.15_Linux-64bit.deb
        sudo dpkg -i trivy_0.0.15_Linux-64bit.deb
      displayName: Docker - Trivy Installation (Container Security Analysis by Aquasec)

    - script: |
        docker build -t '$(dockerId)/$(dockerImageName):latest' ./src
      displayName: Docker - Build

    - script: |
        docker tag '$(dockerId)/$(dockerImageName):latest' '$(dockerId)/$(dockerImageName):$(Build.BuildNumber)'
        docker tag '$(dockerId)/$(dockerImageName):latest' '$(dockerId)/$(dockerImageName):$(Build.SourceVersion)'
      displayName: Docker - Tag

    - script: |
        trivy --only-update alpine '$(dockerId)/$(dockerImageName):$(Build.BuildNumber)'
      displayName: Docker - Trivy Execution (Container Security Analysis by Aquasec)

    - script: |
        docker image list | grep $(dockerId)
      displayName: Docker - List

    - task: Docker@2
      displayName: Docker - Push
      inputs:
        command: push
        containerRegistry: dockerRegistryServiceConnection
        repository: '$(dockerImageName)'
        tags: |
          latest
          $(Build.BuildNumber)
          $(Build.SourceVersion)
