#https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops

name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: $(vmImageName)

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'

stages:
- stage: CI
  #displayName: Build & Test
  jobs:  
  - job: Build & Test
    displayName: Build & Test
    steps:
    - template: templates/dotnet-build-and-test.yml
  - job: Create Docker Image
    dependsOn: Build & Test
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    steps:
    -script: echo Create Docker Image
