#https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops

trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'

stages:
- stage: CI
  displayName: Build and push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: UseDotNet@2
      displayName: 'Use dotnet sdk 3.x'
      inputs:
        version: 3.x
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: 'src/Avalier.Todo.sln'
        arguments: '--configuration Release' # Update this to match your need

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*.Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverageOutputFormat=cobertura /p:CoverletOutput=$(System.DefaultWorkingDirectory)/TestResults/Coverage/'

    #- script: dotnet test <test-project> --logger trx
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: XUnit
        testResultsFiles: '**/*.trx'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/TestResults/Coverage/coverage.json'
        reportDirectory: '$(System.DefaultWorkingDirectory)/TestResults/Coverage/reports'
      displayName: 'Coverage - Publish Results'


   
