
trigger:
- master

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'

stages:
- stage: CI
  displayName: Build and push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - script: |
        echo dockerId: $(dockerId)
        echo tag: $(tag)
        echo connection: dockerRegistryServiceConnection
      displayName: Show variables

    - task: Docker@2
      displayName: Docker - Login
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection

    - script: |
        sudo apt-get -y install trivy
      displayName: Docker - Trivy Installation (Container Security Analysis by Aquasec)

    - script: |
        docker build -t '$(dockerId)/$(dockerImageName):latest' ./src
      displayName: Docker - Build

    - script: |
        trivy '$(dockerId)/$(dockerImageName):latest'
      displayName: Docker - Trivy Execution (Container Security Analysis by Aquasec)

    - script: |
        docker tag '$(dockerId)/$(dockerImageName):latest' '$(dockerId)/$(dockerImageName):$(Build.BuildNumber)'
        docker tag '$(dockerId)/$(dockerImageName):latest' '$(dockerId)/$(dockerImageName):$(Build.SourceVersion)'
      displayName: Docker - Tag

    - script: |
        docker image list | grep $(dockerId)
      displayName: Docker - List

    - task: Docker@2
      displayName: Docker - Push
      inputs:
        command: push
        containerRegistry: dockerRegistryServiceConnection
        repository: '$(dockerImageName)'
        tags: |
          latest
          $(Build.BuildNumber)
          $(Build.SourceVersion)
