# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  dockerId: 'avalier.azurecr.io'
  dockerImageName: 'avalier-todo-be'
  dockerImageLabel: '$(Build.BuildId)'
  tag: '$(dockerId)/${dockerImageName}:$(dockerImageLabel)'
  dockerRegistryServiceConnectionId: '{{ azureDockerRegistry }}'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    #- script: |
    #    #docker build -t $(dockerId)/$(imageName) .
    #    docker login -u $(dockerId) -p $(pswd)
    #    #docker push $(dockerId)/$(imageName)
    #  env:
    #    pswd: $(dockerPassword)
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'src/Dockerfile'
        tags: |
          $(tag)
