pipeline {
    agent any
    stages {
        stage('Build image') {
            steps {
                echo 'Starting to build docker image'

                script {
                    def image = docker.build("avalier/todo:${env.BUILD_ID}")
                    image.push()
                }
            }
        }
    }
}